version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.25.84.144:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-network
    depends_on:
      - zookeeper

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_pgadmin_password
    networks:
      - my-network

  airflow:
    image: apache/airflow:2.2.4
    user: root
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://your_username:your_password@postgres/your_database_name
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8080
      AIRFLOW__WEBSERVER__RBAC: 'True'
      AIRFLOW__WEBSERVER__AUTH_BACKEND: airflow.auth.backends.password_auth
      AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: 'True'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__BASE_LOG_FOLDER: /opt/airflow/logs
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - /home/mhmdghdbn/airflow/zookeeper/airflow/data/output.json:/opt/airflow/data/output.json
      - /home/mhmdghdbn/airflow/zookeeper/airflow/dags:/opt/airflow/dags
      - /home/mhmdghdbn/airflow/zookeeper/airflow/logs:/opt/airflow/logs
      - /home/mhmdghdbn/airflow/zookeeper/requirements.txt:/requirements.txt
      - /home/mhmdghdbn/airflow/zookeeper/airflow/data:/opt/airflow/data
      - /home/mhmdghdbn/airflow/zookeeper/airflow/scripts:/opt/airflow/scripts
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
